update some code
	BUT

	Q: arcsoft_face_sdk.h:146:3: error: unknown type name ‘ASF_DetectMode’

	Need to fix error about compilation

	modified:   pull/Makefile
	new file:   pull/amcomdef.h
	new file:   pull/arcsoft_face_sdk.h
	new file:   pull/asvloffscreen.h
	new file:   pull/face.c
	new file:   pull/merror.h